baseURL = 'https://robindarby.com/'
languageCode = 'en-us'
title = 'Robin Darby'
theme = 'ananke'


[menu]
 [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10


[caches]
  [caches.images]
    dir = ':cacheDir/images'
